image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-card-delivery.jar &
  - chmod +x gradlew


build_script:
<<<<<<< HEAD
  - ./gradlew test --info -Dselenide.headless=true

=======
    - ./gradlew test --info 
    - Dselenide.headless=true
>>>>>>> d0bc77a5ec57343927ee3c7b2d5c19d301343871
